project:
  type: book
  output-dir: "./_output"
  post-render: encrypt.r

book:
  title: "R for marine ecologists: wrangling Earth System Model outputs"
  author: "Jessica Bolin"
  date: "05/29/2025"
  cover-image: images/cmsi.png
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - _x_Acronyms.qmd
    - _xx_about.qmd
    - _xxx_prerequisites.qmd
    - _xxxx_schedule.qmd
    - _1_whatisanesm.qmd
    - _2_downloadesm.qmd
    - _3_regridreproject.qmd
    - _4_oisst.qmd
    - _5_biascorrection.qmd
    - _6_taylordiagrams.qmd
    - _7_projections.qmd
    - _xxxxx_handyresources.qmd
    - _xxxxxx_references.qmd
  repo-url: https://github.com/JessicaBolin/esmRworkshop
  

bibliography: references.bib

format:
  html:
    theme: cosmo
    grid:
      sidebar-width: 400px
      body-width: 800px
      margin-width: 500px
      gutter-width: 1.5rem
  pdf:
    documentclass: scrreprt

editor: visual


